version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql_conf/mysql:/etc/mysql

#  canal-server:
#    image: canal/canal-server
#    container_name: canal-server
#    ports:
#      - 11111:11111
#      - 11110:11110
#      - 11112:11112
#      - 9100:9100
#    environment:
#      canal.instance.master.address: db:3306
#      canal.instance.dbUsername: root
#      canal.instance.dbPassword: password
#      canal.instance.connectionCharset: UTF-8
#      canal.instance.tsdb.enable: "true"
#      canal.instance.gtidon: "false"
#      canal.instance.filter.regex: .*\\..*
#    volumes:
#      - ./cannal_logs:/home/admin/canal-server/logs
#    depends_on:
#      - db
